/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.control_cicil;
import control.control_transaksi;
import control.koneksi;
import control.laporan;
import control.utama;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author N
 */
public class TransaksiCicil extends javax.swing.JFrame {
//    control_transaksi ct;
    control_cicil cc;
    laporan lp;
    koneksi db;
    utama ut;
    

    public String no_cicil;
    public static String id_pelanggan;
    public String nama_pelanggan;
    public static int Kurang, total;
    /**
     * Creates new form TransaksiCicil
     */
    public TransaksiCicil() {
        initComponents();
        Dimension dmax = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(dmax);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setSize(dmax.width,dmax.height);
        this.setLocationRelativeTo(null);
   
        db = new koneksi();
        cc = new control_cicil();
//        ct = new control_transaksi();
        lp = new laporan();
        ut = new utama();
        tbPengeluaran.setModel(cc.model);
        cc.tampilPengeluaran("", "", "",0, 0);
        
        jTable1.setModel(cc.model2);
        cc.tampilansurancicilan("");
//        ct.tampilPengeluaran("", "", 0, 0, 0);
//        ct.noFak();
        setTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        tampilTTL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPengeluaran = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txkode = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        tanggall = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txKasir = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 102));

        tampilTTL.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        tampilTTL.setForeground(new java.awt.Color(255, 255, 255));
        tampilTTL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tampilTTL.setText("0");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilTTL, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilTTL, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        tbPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPengeluaran);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("ITEM BARANG"));

        txkode.setEditable(false);

        txnama.setEditable(false);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_40px.png"))); // NOI18N
        btnCari.setEnabled(false);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_document_40px.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_35px.png"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_40px.png"))); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_35px.png"))); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.setEnabled(false);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel1.setText("NO CICIL");

        jLabel2.setText("NAMA PELANGGAN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txkode, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txnama, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addComponent(jLabel2))
                .addGap(64, 64, 64)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNew)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancel)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txnama)
                        .addComponent(txkode)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PEMBAYARAN CICILAN"));
        jPanel1.setToolTipText("");

        txBayar.setEditable(false);
        txBayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txBayarCaretUpdate(evt);
            }
        });
        txBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBayarActionPerformed(evt);
            }
        });

        jLabel9.setText("Bayar");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_process_70px.png"))); // NOI18N
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SIMPAN");

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_reset_70px.png"))); // NOI18N
        btnReset.setEnabled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("RESET");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_to_70px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset))
                        .addGap(37, 37, 37)
                        .addComponent(jButton1))
                    .addComponent(txBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("Tanggal :");

        tanggall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tanggall.setForeground(new java.awt.Color(0, 204, 204));
        tanggall.setText("2020-03-28");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Kasir :");

        txKasir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txKasir.setForeground(new java.awt.Color(0, 204, 204));
        txKasir.setText("0000");

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("MILOS STORE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tanggall)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel16))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(460, 460, 460)
                        .addComponent(txKasir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggall)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(txKasir)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("PEMBAYARAN CICILAN");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPengeluaranMouseClicked
        // TODO add your handling code here:
        btnhapus.setEnabled(true);
        btnSimpan.setEnabled(false);
        btncancel.setEnabled(true);
    }//GEN-LAST:event_tbPengeluaranMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        frmCariCicilan frm = new frmCariCicilan(null, true,"Cicil");
        frm.setTitle("PILIH");
        frm.setVisible(true);

    }//GEN-LAST:event_btnCariActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        btnCari.setEnabled(true);
        btnNew.setEnabled(false);
        btncancel.setEnabled(true);

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        no_cicil = txkode.getText();
        nama_pelanggan = txnama.getText();

        cc.tampilPengeluaran(no_cicil, id_pelanggan, nama_pelanggan, total, Kurang);
        
        cc.tampilansurancicilan(no_cicil);
        
        tampilTTL.setText(Integer.toString(Kurang));

        btnNew.setEnabled(false);
        btnCari.setEnabled(false);
        btnSimpan.setEnabled(false);
        btncancel.setEnabled(false);
        txBayar.setEditable(true);
        txBayar.requestFocus();

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int row = tbPengeluaran.getSelectedRow();
        cc.model.removeRow(row);
        btnhapus.setEnabled(false);
        btncancel.setEnabled(false);
        btnNew.setEnabled(true);
        btnCari.setEnabled(false);

        int subTotal = 0;
 
        tampilTTL.setText(Integer.toString(subTotal));
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        btncancel.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnNew.setEnabled(true);
        btnCari.setEnabled(false);
        btnhapus.setEnabled(false);

        tbPengeluaran.clearSelection();
    }//GEN-LAST:event_btncancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormUtama.user.setText(txKasir.getText());
        ut.tampilCountTrx();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cc.model.removeRow(0);
        cc.model2.removeRow(0);
        tampilTTL.setText("0");
        tbPengeluaran.removeAll();
        jTable1.removeAll();
        //        cc.noFak();
        //        txDiskon.setText("0");
        txBayar.setText("");
        txBayar.setEditable(false);
        //        txDiskon.setEditable(false);
        cc.model.setRowCount(0);
        cc.model2.setRowCount(0);
        btnReset.setEnabled(false);
        //        btnCariPlg.setEnabled(false);
        btnSave.setEnabled(false);
        btnNew.setEnabled(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int total_awal = total;
        int total_akhir, pkurang;
        pkurang = Kurang;
        int totalKurang;
        int kurang;
        kurang = Kurang;
        kurang *= -1;
        totalKurang = kurang + Integer.parseInt(txBayar.getText());

        //        JOptionPane.showMessageDialog(rootPane, "Kurang " + totalKurang);

        int bayarke ;

        int bayar = Integer.parseInt(txBayar.getText());

        total_akhir = total_awal - pkurang  + bayar;

        if (total_akhir > total_awal) {
            JOptionPane.showMessageDialog(rootPane, "Pembayaran Melebihi!!");
            return;
        }
        //        JOptionPane.showMessageDialog(rootPane, total_akhir);

        String tanggal = tanggall.getText();

        try{
            db.setKoneksi();
            String sql1 = "SELECT COUNT(*) as pembayaranke from transaksicicil where no_cicil='" + txkode.getText() + "' ";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(sql1);
            rs.next();
            int ke = rs.getInt("pembayaranke");

            //            JOptionPane.showMessageDialog(rootPane,ke);
            bayarke = ke + 1;
            cc.transaksiCicilan(no_cicil, bayarke, bayar, tanggal);

            cc.updateCicil(no_cicil, total_akhir,  totalKurang);
            JOptionPane.showMessageDialog(rootPane, "DATA CICILAN BERHASIL DI SIMPAN");

        } catch(SQLException ex){
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnSave.setEnabled(false);
        btnNew.setEnabled(false);
        txkode.setEnabled(false);
        txnama.setEnabled(false);

        //        if(bayar<total){
            //            JOptionPane.showMessageDialog(rootPane, "Jika Pembayaran Kurang Klik Tombol Cicil");
            //        }else{
            //            for(int n = 0;n<tbPengeluaran.getRowCount();n++){
                //                try {
                    //                    String kode_barang = (String) tbPengeluaran.getValueAt(n, 0);
                    //                    String nama_barang = (String) tbPengeluaran.getValueAt(n, 1);
                    //                    int harga = (int) tbPengeluaran.getValueAt(n, 2);
                    //                    int qty = (int) tbPengeluaran.getValueAt(n, 3);
                    //                    int totall = (int) tbPengeluaran.getValueAt(n, 4);
                    //                    db.setKoneksi();
                    //                    String sqli = "SELECT stok from masterBarang where kode_barang = '"+kode_barang+"'";
                    //                    Statement st = db.getKoneksi().createStatement();
                    //                    ResultSet rs = st.executeQuery(sqli);
                    //                    while(rs.next()){
                        //                        int stok = rs.getInt("stok");
                        //                        int sisa = stok - qty;
                        ////                        ct.updateStok(sisa, kode_barang);
                        //
                        //                    }
                    //                    try {
                        //                        cc.insertBarang(nofak, kode_barang, nama_barang, harga, qty, totall);
                        //                    } catch (SQLException ex) {
                        //                        Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
                        //                    }
                    //                } catch (SQLException ex) {
                    //                    Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
                    //                }
                //            }
            //
            //            try {
                //                cc.transaksiCicilan(no_cicil ,id_pelanggan, nama_pelanggan, Kurang, bayarke, bayar,kembali,tanggal);
                //                JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI SIMPAN");
                //
                //                //            ct.noFak();
                //            } catch (SQLException ex) {
                //                Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //
            //            btnSave.setEnabled(false);
            //            btnCicil.setEnabled(false);
            //            btnCetak.setEnabled(true);

            //            btnNew.setEnabled(false);
            //        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txBayarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txBayarCaretUpdate
        // TODO add your handling code here:
        if(txBayar.getText().length()>0){
            int bayar = Integer.parseInt(txBayar.getText());

            btnSave.setEnabled(true);
            btnReset.setEnabled(true);

        }
    }//GEN-LAST:event_txBayarCaretUpdate

    private void txBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiCicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiCicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiCicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiCicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiCicil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    public static javax.swing.JButton btnSimpan;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel tampilTTL;
    private javax.swing.JLabel tanggall;
    private javax.swing.JTable tbPengeluaran;
    private javax.swing.JTextField txBayar;
    public static javax.swing.JLabel txKasir;
    public static javax.swing.JTextField txkode;
    public static javax.swing.JTextField txnama;
    // End of variables declaration//GEN-END:variables

    private void setTanggal() {
        Date tgl = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        tanggall.setText(format.format(tgl));
    }
}
